services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: procat
    ports:
      - "5432:5432"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
