// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID              pgtype.UUID
	SchemaVersionID pgtype.UUID
	Name            string
	Description     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ProductComposition struct {
	ID                   pgtype.UUID
	ParentProductID      pgtype.UUID
	SchemaVersionFieldID pgtype.UUID
	ChildProductID       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type ProductField struct {
	ID                   pgtype.UUID
	ProductID            pgtype.UUID
	SchemaVersionFieldID pgtype.UUID
	Value                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type Schema struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type SchemaVersion struct {
	ID        pgtype.UUID
	SchemaID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type SchemaVersionField struct {
	ID                 pgtype.UUID
	SchemaVersionID    pgtype.UUID
	Name               string
	DataType           string
	IsRequired         bool
	DefaultValue       pgtype.Text
	ValidationRules    []string
	RefSchemaVersionID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}
